[general]
import = [ "~/.config/alacritty/themes/themes/gruvbox_dark.toml" ]

[env]
TERM = "xterm-256color"
http_proxy="http://127.0.0.1:2080"
https_proxy="http://127.0.0.1:2080"
all_proxy="socks5://127.0.0.1:2080"
ALL_PROXY="socks5://127.0.0.1:2080"

[selection]
save_to_clipboard = true

[font]
normal.family = "JetbrainsMono"
